<section class="cube">
  <h3>Cube</h3>

  <div class="cube__wrap">
  	<div class="cube3d">
  		<div class="cube3d__face cube3d__face--front">front</div>
  		<div class="cube3d__face cube3d__face--back">back</div>
  		<div class="cube3d__face cube3d__face--top">top</div>
  		<div class="cube3d__face cube3d__face--bottom">bottom</div>
  		<div class="cube3d__face cube3d__face--left">left</div>
  		<div class="cube3d__face cube3d__face--right">right</div>
  	</div>
  </div>
</sectipn>
